name: Cache build artifacts

on:
  pull_request:
    branches: ['master']
    types:
      - opened
      - reopened
      - synchronize
      # we skip ci for draft PRs
      # https://github.com/reviewdog/action-eslint/issues/29#issuecomment-985939887
      - ready_for_review
  workflow_call:

env:
  NEXT_PUBLIC_RPC_PROVIDER: alchemy
  NEXT_PUBLIC_INFURA_KEY: ${{ secrets.NEXT_PUBLIC_INFURA_KEY }}
  NEXT_PUBLIC_ALCHEMY_KEY: ${{ secrets.NEXT_PUBLIC_ALCHEMY_KEY }}
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID }}
  VAULTS_FYI_API_KEY: ${{ secrets.VAULTS_FYI_API_KEY }}
  THE_GRAPH_NETWORK_API_KEY: ${{ secrets.THE_GRAPH_NETWORK_API_KEY }}
  INDEXER_API_URL_BY_CHAIN: ${{ secrets.INDEXER_API_URL_BY_CHAIN }}
  NEXT_PUBLIC_INDEXER_CHILD_CHAIN_IDS: ${{ secrets.NEXT_PUBLIC_INDEXER_CHILD_CHAIN_IDS }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-build-cache:
    name: Check cache for build artifacts
    runs-on: ubuntu-4
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node 22
        uses: actions/setup-node@v5
        with:
          node-version: 22
          package-manager-cache: false

      - name: Check cache for build artifacts
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ./packages/app/build
            ./packages/app/public/__auto-generated-*
          key: build-artifacts-${{ github.run_id }}

      - name: Install node_modules
        if: steps.cache.outputs.cache-hit != 'true'
        uses: OffchainLabs/actions/node-modules/install@main
        with:
          install-command: pnpm install --frozen-lockfile
          cache-key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Build
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash
        run: pnpm build
        env:
          NEXT_PUBLIC_IS_E2E_TEST: true
          NEXT_PUBLIC_RPC_PROVIDER: alchemy
          NEXT_PUBLIC_INFURA_KEY: ${{ secrets.NEXT_PUBLIC_INFURA_KEY }}
          NEXT_PUBLIC_ALCHEMY_KEY: ${{ secrets.NEXT_PUBLIC_ALCHEMY_KEY }}
          NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID }}
          THE_GRAPH_NETWORK_API_KEY: ${{ secrets.THE_GRAPH_NETWORK_API_KEY }}
          INDEXER_API_URL_BY_CHAIN: ${{ secrets.INDEXER_API_URL_BY_CHAIN }}
          NEXT_PUBLIC_INDEXER_CHILD_CHAIN_IDS: ${{ secrets.NEXT_PUBLIC_INDEXER_CHILD_CHAIN_IDS }}

      - name: Cache build artifacts
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            ./packages/app/build
            ./packages/app/public/__auto-generated-*
          key: build-artifacts-${{ github.run_id }}
